"""create_product_embeddings_table

Revision ID: 70f0c7f28370
Revises: a2c0bda2164d
Create Date: 2026-09-15 19:50:36.420082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f0c7f28370'
down_revision: Union[str, Sequence[str], None] = 'a2c0bda2164d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('builder_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_embeddings_content_hash'), 'product_embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_product_embeddings_id'), 'product_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_product_embeddings_product_id'), 'product_embeddings', ['product_id'], unique=True)
    op.create_index(op.f('ix_product_embeddings_vector_id'), 'product_embeddings', ['vector_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_embeddings_vector_id'), table_name='product_embeddings')
    op.drop_index(op.f('ix_product_embeddings_product_id'), table_name='product_embeddings')
    op.drop_index(op.f('ix_product_embeddings_id'), table_name='product_embeddings')
    op.drop_index(op.f('ix_product_embeddings_content_hash'), table_name='product_embeddings')
    op.drop_table('product_embeddings')
    # ### end Alembic commands ###
